# Generated by Django 2.1.4 on 2019-01-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20190105_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('1', 'Kid A'), ('2', 'The dark side of the moon')], max_length=1),
        ),
    ]
